# Generated by Django 3.2.9 on 2021-12-08 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0002_auto_20211208_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='expirationDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='integration',
            name='issueDate',
            field=models.DateTimeField(),
        ),
    ]
