# Generated by Django 3.2.9 on 2021-12-29 06:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcc_number', models.IntegerField(verbose_name='dccnumber')),
                ('license_number', models.CharField(max_length=225, verbose_name='licenseNumber')),
                ('license_status', models.CharField(max_length=225, verbose_name='licenseStatus')),
                ('license_status_date', models.DateField(blank=True, default=None, null=True, verbose_name='licenseStatusDate')),
                ('license_term', models.CharField(blank=True, default=None, max_length=225, null=True, verbose_name='licenseTerm')),
                ('license_type', models.CharField(max_length=225, verbose_name='licenseType')),
                ('license_designation', models.CharField(blank=True, default=None, max_length=225, null=True, verbose_name='licenseDesignation')),
                ('issue_date', models.DateField(verbose_name='issueDate')),
                ('expiration_date', models.DateField(verbose_name='expirationDate')),
                ('licensing_authority_id', models.CharField(blank=True, default=None, max_length=225, null=True, verbose_name='licensingAuthorityId')),
                ('licensing_authority', models.CharField(blank=True, default=None, max_length=225, null=True, verbose_name='licensingAuthority')),
                ('business_legal_name', models.CharField(max_length=500, verbose_name='businessLegalName')),
                ('business_dba_name', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='businessDbaName')),
                ('business_owner_name', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='businessOwnerName')),
                ('business_structure', models.CharField(blank=True, default=None, max_length=225, null=True, verbose_name='businessStructure')),
                ('activity', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=225), blank=True, default=list, null=True, size=None)),
                ('premise_street_address', models.CharField(blank=True, default=None, max_length=225, null=True, verbose_name='premiseStreetAddress')),
                ('premise_city', models.CharField(blank=True, default=None, max_length=225, null=True, verbose_name='premiseCity')),
                ('premise_state', models.CharField(blank=True, default=None, max_length=225, null=True, verbose_name='premiseState')),
                ('premise_county', models.CharField(blank=True, default=None, max_length=225, null=True, verbose_name='premiseCounty')),
                ('premise_zip_code', models.CharField(blank=True, default=None, max_length=225, null=True, verbose_name='premiseZipCode')),
                ('business_email', models.CharField(max_length=225, verbose_name='businessEmail')),
                ('business_phone', models.CharField(blank=True, default=None, max_length=225, null=True, verbose_name='businessPhone')),
                ('parcel_number', models.CharField(blank=True, default=None, max_length=225, null=True, verbose_name='parcelNumber')),
                ('premise_latitude', models.FloatField(blank=True, default=None, null=True, verbose_name='premiseLatitude')),
                ('premise_longitude', models.FloatField(blank=True, default=None, null=True, verbose_name='premiseLongitude')),
                ('data_refreshed_date', models.DateTimeField(verbose_name='dataRefreshedDate')),
            ],
        ),
    ]
