# Generated by Django 3.2.9 on 2021-12-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dccnumber', models.IntegerField()),
                ('licenseNumber', models.CharField(max_length=100)),
                ('licenseStatus', models.CharField(max_length=100)),
                ('licenseStatusDate', models.CharField(max_length=100, null=True)),
                ('licenseTerm', models.CharField(max_length=100)),
                ('licenseType', models.CharField(max_length=100)),
                ('licenseDesignation', models.CharField(max_length=100)),
                ('issueDate', models.CharField(max_length=100)),
                ('expirationDate', models.CharField(max_length=100)),
                ('licensingAuthorityId', models.CharField(max_length=100)),
                ('licensingAuthority', models.CharField(max_length=100)),
                ('businessLegalName', models.CharField(max_length=100)),
                ('businessDbaName', models.CharField(max_length=100)),
                ('businessOwnerName', models.CharField(max_length=100)),
                ('businessStructure', models.CharField(max_length=100)),
                ('activity', models.CharField(max_length=100)),
                ('premiseStreetAddress', models.CharField(max_length=100)),
                ('premiseCity', models.CharField(max_length=100)),
                ('premiseState', models.CharField(max_length=100)),
                ('premiseCounty', models.CharField(max_length=100)),
                ('premiseZipCode', models.CharField(max_length=100)),
                ('businessEmail', models.CharField(max_length=100)),
                ('businessPhone', models.CharField(max_length=100)),
                ('parcelNumber', models.CharField(max_length=100)),
                ('premiseLatitude', models.IntegerField(null=True)),
                ('premiseLongitude', models.IntegerField(null=True)),
                ('dataRefreshedDate', models.DateTimeField()),
            ],
        ),
    ]
