# Generated by Django 3.2.9 on 2021-12-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0003_auto_20211208_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='businessOwnerName',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='integration',
            name='licenseStatusDate',
            field=models.DateTimeField(null=True),
        ),
    ]
