# Generated by Django 3.2.9 on 2021-12-23 11:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0004_auto_20211208_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integration',
            name='businessDbaName',
        ),
        migrations.RemoveField(
            model_name='integration',
            name='businessEmail',
        ),
        migrations.RemoveField(
            model_name='integration',
            name='businessLegalName',
        ),
        migrations.RemoveField(
            model_name='integration',
            name='businessOwnerName',
        ),
        migrations.RemoveField(
            model_name='integration',
            name='businessPhone',
        ),
        migrations.RemoveField(
            model_name='integration',
            name='businessStructure',
        ),
        migrations.RemoveField(
            model_name='integration',
            name='dataRefreshedDate',
        ),
        migrations.RemoveField(
            model_name='integration',
            name='dccnumber',
        ),
        migrations.RemoveField(
            model_name='integration',
            name='expirationDate',
        ),
        migrations.RemoveField(
            model_name='integration',
            name='issueDate',
        ),
        migrations.RemoveField(
            model_name='integration',
            name='licenseDesignation',
        ),
        migrations.RemoveField(
            model_name='integration',
            name='licenseNumber',
        ),
        migrations.RemoveField(
            model_name='integration',
            name='licenseStatus',
        ),
        migrations.RemoveField(
            model_name='integration',
            name='licenseStatusDate',
        ),
        migrations.RemoveField(
            model_name='integration',
            name='licenseTerm',
        ),
        migrations.RemoveField(
            model_name='integration',
            name='licenseType',
        ),
        migrations.RemoveField(
            model_name='integration',
            name='licensingAuthority',
        ),
        migrations.RemoveField(
            model_name='integration',
            name='licensingAuthorityId',
        ),
        migrations.RemoveField(
            model_name='integration',
            name='parcelNumber',
        ),
        migrations.RemoveField(
            model_name='integration',
            name='premiseCity',
        ),
        migrations.RemoveField(
            model_name='integration',
            name='premiseCounty',
        ),
        migrations.RemoveField(
            model_name='integration',
            name='premiseLatitude',
        ),
        migrations.RemoveField(
            model_name='integration',
            name='premiseLongitude',
        ),
        migrations.RemoveField(
            model_name='integration',
            name='premiseState',
        ),
        migrations.RemoveField(
            model_name='integration',
            name='premiseStreetAddress',
        ),
        migrations.RemoveField(
            model_name='integration',
            name='premiseZipCode',
        ),
        migrations.AddField(
            model_name='integration',
            name='business_dba_name',
            field=models.CharField(default=None, max_length=225, verbose_name='businessDbaName'),
        ),
        migrations.AddField(
            model_name='integration',
            name='business_email',
            field=models.CharField(default=None, max_length=225, verbose_name='businessEmail'),
        ),
        migrations.AddField(
            model_name='integration',
            name='business_legal_name',
            field=models.CharField(default=None, max_length=225, verbose_name='businessLegalName'),
        ),
        migrations.AddField(
            model_name='integration',
            name='business_owner_name',
            field=models.CharField(default=None, max_length=225, verbose_name='businessOwnerName'),
        ),
        migrations.AddField(
            model_name='integration',
            name='business_phone',
            field=models.CharField(default=None, max_length=225, verbose_name='businessPhone'),
        ),
        migrations.AddField(
            model_name='integration',
            name='business_structure',
            field=models.CharField(default=None, max_length=225, verbose_name='businessStructure'),
        ),
        migrations.AddField(
            model_name='integration',
            name='data_refreshed_date',
            field=models.DateTimeField(default=None, verbose_name='dataRefreshedDate'),
        ),
        migrations.AddField(
            model_name='integration',
            name='dcc_number',
            field=models.IntegerField(default=None, verbose_name='dccnumber'),
        ),
        migrations.AddField(
            model_name='integration',
            name='expiration_date',
            field=models.DateField(default=None, verbose_name='expirationDate'),
        ),
        migrations.AddField(
            model_name='integration',
            name='issue_date',
            field=models.DateField(default=None, verbose_name='issueDate'),
        ),
        migrations.AddField(
            model_name='integration',
            name='license_designation',
            field=models.CharField(default=None, max_length=225, verbose_name='licenseDesignation'),
        ),
        migrations.AddField(
            model_name='integration',
            name='license_number',
            field=models.CharField(default=None, max_length=225, verbose_name='licenseNumber'),
        ),
        migrations.AddField(
            model_name='integration',
            name='license_status',
            field=models.CharField(default=None, max_length=225, verbose_name='licenseStatus'),
        ),
        migrations.AddField(
            model_name='integration',
            name='license_status_date',
            field=models.DateField(default=None, null=True, verbose_name='licenseStatusDate'),
        ),
        migrations.AddField(
            model_name='integration',
            name='license_term',
            field=models.CharField(default=None, max_length=225, verbose_name='licenseTerm'),
        ),
        migrations.AddField(
            model_name='integration',
            name='license_type',
            field=models.CharField(default=None, max_length=225, verbose_name='licenseType'),
        ),
        migrations.AddField(
            model_name='integration',
            name='licensing_authority',
            field=models.CharField(default=None, max_length=225, verbose_name='licensingAuthority'),
        ),
        migrations.AddField(
            model_name='integration',
            name='licensing_authority_id',
            field=models.CharField(default=None, max_length=225, verbose_name='licensingAuthorityId'),
        ),
        migrations.AddField(
            model_name='integration',
            name='parcel_number',
            field=models.CharField(default=None, max_length=225, verbose_name='parcelNumber'),
        ),
        migrations.AddField(
            model_name='integration',
            name='premise_city',
            field=models.CharField(default=None, max_length=225, verbose_name='premiseCity'),
        ),
        migrations.AddField(
            model_name='integration',
            name='premise_county',
            field=models.CharField(default=None, max_length=225, verbose_name='premiseCounty'),
        ),
        migrations.AddField(
            model_name='integration',
            name='premise_latitude',
            field=models.IntegerField(default=None, null=True, verbose_name='premiseLatitude'),
        ),
        migrations.AddField(
            model_name='integration',
            name='premise_longitude',
            field=models.IntegerField(default=None, null=True, verbose_name='premiseLongitude'),
        ),
        migrations.AddField(
            model_name='integration',
            name='premise_state',
            field=models.CharField(default=None, max_length=225, verbose_name='premiseState'),
        ),
        migrations.AddField(
            model_name='integration',
            name='premise_street_address',
            field=models.CharField(default=None, max_length=225, verbose_name='premiseStreetAddress'),
        ),
        migrations.AddField(
            model_name='integration',
            name='premise_zip_code',
            field=models.CharField(default=None, max_length=225, verbose_name='premiseZipCode'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='activity',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None),
        ),
    ]
