# Generated by Django 3.2.9 on 2021-12-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0005_auto_20211223_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='business_dba_name',
            field=models.CharField(default='None', max_length=225, verbose_name='businessDbaName'),
        ),
    ]
