# Generated by Django 3.2.9 on 2021-12-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0007_alter_integration_business_dba_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='business_dba_name',
            field=models.CharField(default=None, max_length=225, verbose_name='businessDbaName'),
        ),
    ]
