# Generated by Django 3.2.9 on 2021-12-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0009_alter_integration_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='business_dba_name',
            field=models.CharField(default=None, max_length=500, verbose_name='businessDbaName'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='business_legal_name',
            field=models.CharField(default=None, max_length=500, verbose_name='businessLegalName'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='business_owner_name',
            field=models.CharField(default=None, max_length=500, verbose_name='businessOwnerName'),
        ),
    ]
