# Generated by Django 3.2.9 on 2021-12-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0010_auto_20211223_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='premise_latitude',
            field=models.FloatField(default=None, null=True, verbose_name='premiseLatitude'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='premise_longitude',
            field=models.FloatField(default=None, null=True, verbose_name='premiseLongitude'),
        ),
    ]
