# Generated by Django 3.2.9 on 2021-12-29 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0016_alter_integration_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='business_dba_name',
            field=models.CharField(max_length=500, verbose_name='businessDbaName'),
        ),
    ]
