# Generated by Django 3.2.9 on 2021-12-29 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0017_alter_integration_business_dba_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='business_dba_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='businessDbaName'),
        ),
    ]
