from django.db import models

class Integration(models.Model):
    dccnumber = models.IntegerField()
    licenseNumber = models.CharField(max_length=225)
    licenseStatus = models.CharField(max_length=225)
    licenseStatusDate = models.DateTimeField(null=True)
    licenseTerm = models.CharField(max_length=225)
    licenseType = models.CharField(max_length=225)
    licenseDesignation = models.CharField(max_length=225)
    issueDate = models.DateTimeField()
    expirationDate = models.DateTimeField()
    licensingAuthorityId = models.CharField(max_length=225)
    licensingAuthority = models.CharField(max_length=225)
    businessLegalName = models.CharField(max_length=225)
    businessDbaName = models.CharField(max_length=225)
    businessOwnerName = models.CharField(max_length=500)
    businessStructure = models.CharField(max_length=225)
    activity = models.CharField(max_length=225)
    premiseStreetAddress = models.CharField(max_length=225)
    premiseCity = models.CharField(max_length=225)
    premiseState = models.CharField(max_length=225)
    premiseCounty = models.CharField(max_length=225)
    premiseZipCode = models.CharField(max_length=225)
    businessEmail = models.CharField(max_length=225)
    businessPhone = models.CharField(max_length=225)
    parcelNumber = models.CharField(max_length=225)
    premiseLatitude = models.IntegerField(null=True)
    premiseLongitude = models.IntegerField(null=True)
    dataRefreshedDate = models.DateTimeField()
